input 
{
	tcp
	{
		port => 5003
		codec => json
		tags => ["ldap"]
	}
}
filter
{
	if "ldap" in [tags]
	{
                date
                {
                        match => [ "time", "MMM dd HH:mm:ss", "MMM  d HH:mm:ss" ]
                        target => "@timestamp"
                        timezone => "America/Sao_Paulo"
                }
                ruby
                {
                            code => "
                              require 'tzinfo' # Make sure TZInfo is loaded

                              if event.get('@timestamp')
                                # Get the UTC timestamp from @timestamp
                                utc_time = event.get('@timestamp').time

                                # Get the timezone object for America/Sao_Paulo
                                # Ensure this string matches your timezone EXACTLY
                                tz = TZInfo::Timezone.get('America/Sao_Paulo')

                                # Convert the UTC time to the local time within that timezone
                                # This gives you a TZInfo::TimeWithZone object
                                local_time_with_zone = tz.to_local(utc_time)

                                # Now extract the components from the local_time_with_zone object
                                event.set('hour_of_day', local_time_with_zone.hour)
                                event.set('day_of_week', local_time_with_zone.wday)
                                event.set('day_of_name', local_time_with_zone.strftime('%A'))
                              end
                            "
                }
                translate
                {
                        source => "[user]"
                        target => "[city]"
                        dictionary_path => "/etc/logstash/dictionaries/sldap/city.yml"
                }
                translate
                {
                        source => "[user]"
                        target => "[telephoneNumber]"
                        dictionary_path => "/etc/logstash/dictionaries/sldap/telephoneNumber.yml"
                }
                translate
                {
                        source => "[user]"
                        target => "[uid]"
                        dictionary_path => "/etc/logstash/dictionaries/sldap/uid.yml"
                }
                translate
                {
                        source => "[user]"
                        target => "[uidNumber]"
                        dictionary_path => "/etc/logstash/dictionaries/sldap/uidNumber.yml"
                }
	}
}
#PUT _index_template/ldap-template
#{
#  "index_patterns": ["ldap-*"],
#  "template": {
#    "mappings": {
#      "properties": {
#        "server": { "type": "ip" },
#        "client": { "type": "ip" }
#      }
#    }
#  },
#  "priority": 500
#}
output
{
        if "ldap" in [tags]
        {
                elasticsearch
                {
                        hosts => ["https://localhost:9200"]
                        index => "ldap-%{+YYYY.MM}"
                        user  => "elastic"
                        password => "..."
                        ssl_verification_mode => none
                }
        }
}
